version: '3.8'

services:

  Config-service:
    build:
      context: ./Config-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/config-service:latest  # Replace "username" with your Docker Hub username

  Discovery:
    build:
      context: ./Discovery
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/discovery:latest  # Replace "username" with your Docker Hub username

  Student:
    build:
      context: ./Student  # Path to service2 directory
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/student:latest

  Teacher:
    build:
      context: ./Teacher  # Path to service3 directory
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/teacher:latest

  video-test:
    build:
      context: ./video-test  # Path to service3 directory
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/video-test:latest


  Gateway-Service:
    build:
      context: ./Gateway-Service  # Path to service3 directory
      dockerfile: dockerfile
    image: ${DOCKERHUB_USERNAME}/gateway-service:latest


  Security-Microservice:
    build:
      context: ./Security_Microservice  # Path to service3 directory
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/security_microservice:latest



  Cour:
    build:
      context: ./Cour  # Path to service3 directory
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/cour:latest


