name: Edu-Connect CI CD Pipeline
on:
  push:
    
    branches: [ "main" ]
    paths:
      - 'Config-service/**'
      - 'Discovery/**'
      - 'Student/**'
      - 'Teacher/**'
      - 'video-test/**'
      - 'Gateway-Service/**'
      - 'Security_Microservice/**'
      - 'Cour/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
            cache-dependency-path: '**/pom.xml'  # Ajouté pour supporter les multiples pom.xml

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

        
    - name: Build all services with Maven
      run: |
        for dir in Config-service Discovery Student Teacher video-test Gateway-Service Security_Microservice Cour; do
          if [ -f "$dir/pom.xml" ]; then
            echo "Building $dir"
            cd $dir
            mvn clean package -DskipTests
            cd ..
          fi
        done


    - name: SonarCloud Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=mohamed-alaoui6_edu-connect-ci-cd \
          -Dsonar.organization=mohamed-alaoui6 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARTOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker images
      run: docker-compose build


    - name: Run Trivy Scan with Retry
      run: |
        for i in {1..3}; do
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/trivy-cache:/root/.cache/trivy aquasec/trivy:latest image $GITHUB_SHA && break || sleep 60
        done




    - name: Push discovery image
      run: |
          docker tag cha7pala/discovery:latest $DOCKERHUB_USERNAME/discovery:latest
          docker push $DOCKERHUB_USERNAME/discovery:latest


    - name: Push Config-service image
      run: |
          docker tag cha7pala/config-service:latest $DOCKERHUB_USERNAME/config-service:latest
          docker push $DOCKERHUB_USERNAME/config-service:latest



    - name: Push student image
      run: |
          docker tag cha7pala/student:latest $DOCKERHUB_USERNAME/student:latest
          docker push $DOCKERHUB_USERNAME/student:latest




    - name: Push teacher image
      run: |
          docker tag cha7pala/teacher:latest $DOCKERHUB_USERNAME/teacher:latest
          docker push $DOCKERHUB_USERNAME/teacher:latest





    - name: Push video-test image
      run: |
          docker tag cha7pala/video-test:latest $DOCKERHUB_USERNAME/video-test:latest
          docker push $DOCKERHUB_USERNAME/video-test:latest





    - name: Push gateway image
      run: |
          docker tag cha7pala/gateway-service:latest $DOCKERHUB_USERNAME/gateway-service:latest
          docker push $DOCKERHUB_USERNAME/gateway-service:latest




    - name: Push security image
      run: |
          docker tag cha7pala/security_microservice:latest $DOCKERHUB_USERNAME/security_microservice:latest
          docker push $DOCKERHUB_USERNAME/security_microservice:latest




    - name: Push cours image
      run: |
          docker tag cha7pala/cour:latest $DOCKERHUB_USERNAME/cour:latest
          docker push $DOCKERHUB_USERNAME/cour:latest



#- name: Push Docker images
 #     run: |
#        for service in discovery student teacher video gateway security cours; do
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
#        done
    


    
